name: Publish to GitHub Pages

on:
  [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.x'
      
      - run: yarn install
      - name: Build Eleventy
        run: yarn build
        env:
          WEB_PATH_PREFIX: /Atmosphere/
          WEB_ROOT_URL: https://danador.github.io/
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./_site
